CREATE TABLE user_table(
user_id varchar(12) not null ,
password varchar(15) not null,
name varchar(12) not null,
point integer,
item_list varchar(100),
PRIMARY KEY(user_id)
);

create table item(
item_id long generated by default as identity,
filename varchar(40) not null,
point int,
upload_date date,
tags_str varchar(50),
primary key(item_id)
);